// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5W5yXe1MMTtk-irDD2ky4fzvs3H4PUg4',
    appId: '1:983659827197:web:0815cb80484135f47e5394',
    messagingSenderId: '983659827197',
    projectId: 'chat-app-a77bc',
    authDomain: 'chat-app-a77bc.firebaseapp.com',
    storageBucket: 'chat-app-a77bc.appspot.com',
    measurementId: 'G-TQG2DFKL0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2gE_hTuyODvNMZsK0fajEbs2PGBPQtFk',
    appId: '1:983659827197:android:c4f34e94f513920d7e5394',
    messagingSenderId: '983659827197',
    projectId: 'chat-app-a77bc',
    storageBucket: 'chat-app-a77bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALtkOfV-FQlUNfEWEuu-WL3zW7MgB1lPQ',
    appId: '1:983659827197:ios:37232c8c455b17867e5394',
    messagingSenderId: '983659827197',
    projectId: 'chat-app-a77bc',
    storageBucket: 'chat-app-a77bc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALtkOfV-FQlUNfEWEuu-WL3zW7MgB1lPQ',
    appId: '1:983659827197:ios:37232c8c455b17867e5394',
    messagingSenderId: '983659827197',
    projectId: 'chat-app-a77bc',
    storageBucket: 'chat-app-a77bc.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5W5yXe1MMTtk-irDD2ky4fzvs3H4PUg4',
    appId: '1:983659827197:web:5463316f337378457e5394',
    messagingSenderId: '983659827197',
    projectId: 'chat-app-a77bc',
    authDomain: 'chat-app-a77bc.firebaseapp.com',
    storageBucket: 'chat-app-a77bc.appspot.com',
    measurementId: 'G-PV4KXV00RN',
  );

}